/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InfluenciaRouteImport } from './routes/influencia'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as AutomationsIdRouteImport } from './routes/automations.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluenciaRoute = InfluenciaRouteImport.update({
  id: '/influencia',
  path: '/influencia',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsIdRoute = AutomationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AutomationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRouteWithChildren
  '/campanhas': typeof CampanhasRoute
  '/dashboard': typeof DashboardRoute
  '/influencia': typeof InfluenciaRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/automations/$id': typeof AutomationsIdRoute
  '/campaigns/$id': typeof CampaignsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRouteWithChildren
  '/campanhas': typeof CampanhasRoute
  '/dashboard': typeof DashboardRoute
  '/influencia': typeof InfluenciaRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/automations/$id': typeof AutomationsIdRoute
  '/campaigns/$id': typeof CampaignsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRouteWithChildren
  '/campanhas': typeof CampanhasRoute
  '/dashboard': typeof DashboardRoute
  '/influencia': typeof InfluenciaRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/automations/$id': typeof AutomationsIdRoute
  '/campaigns/$id': typeof CampaignsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/campanhas'
    | '/dashboard'
    | '/influencia'
    | '/login'
    | '/settings'
    | '/automations/$id'
    | '/campaigns/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/campanhas'
    | '/dashboard'
    | '/influencia'
    | '/login'
    | '/settings'
    | '/automations/$id'
    | '/campaigns/$id'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/campanhas'
    | '/dashboard'
    | '/influencia'
    | '/login'
    | '/settings'
    | '/automations/$id'
    | '/campaigns/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRouteWithChildren
  CampanhasRoute: typeof CampanhasRoute
  DashboardRoute: typeof DashboardRoute
  InfluenciaRoute: typeof InfluenciaRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencia': {
      id: '/influencia'
      path: '/influencia'
      fullPath: '/influencia'
      preLoaderRoute: typeof InfluenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations/$id': {
      id: '/automations/$id'
      path: '/$id'
      fullPath: '/automations/$id'
      preLoaderRoute: typeof AutomationsIdRouteImport
      parentRoute: typeof AutomationsRoute
    }
  }
}

interface AutomationsRouteChildren {
  AutomationsIdRoute: typeof AutomationsIdRoute
}

const AutomationsRouteChildren: AutomationsRouteChildren = {
  AutomationsIdRoute: AutomationsIdRoute,
}

const AutomationsRouteWithChildren = AutomationsRoute._addFileChildren(
  AutomationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRouteWithChildren,
  CampanhasRoute: CampanhasRoute,
  DashboardRoute: DashboardRoute,
  InfluenciaRoute: InfluenciaRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  CampaignsIdRoute: CampaignsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
