/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InfluenciaRouteImport } from './routes/influencia'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as AnalisarRouteImport } from './routes/analisar'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsIdRouteImport } from './routes/campaigns.$id'
import { Route as AutomationIdRouteImport } from './routes/automation.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InfluenciaRoute = InfluenciaRouteImport.update({
  id: '/influencia',
  path: '/influencia',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalisarRoute = AnalisarRouteImport.update({
  id: '/analisar',
  path: '/analisar',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsIdRoute = CampaignsIdRouteImport.update({
  id: '/campaigns/$id',
  path: '/campaigns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationIdRoute = AutomationIdRouteImport.update({
  id: '/automation/$id',
  path: '/automation/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analisar': typeof AnalisarRoute
  '/automations': typeof AutomationsRoute
  '/campanhas': typeof CampanhasRoute
  '/dashboard': typeof DashboardRoute
  '/influencia': typeof InfluenciaRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/automation/$id': typeof AutomationIdRoute
  '/campaigns/$id': typeof CampaignsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analisar': typeof AnalisarRoute
  '/automations': typeof AutomationsRoute
  '/campanhas': typeof CampanhasRoute
  '/dashboard': typeof DashboardRoute
  '/influencia': typeof InfluenciaRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/automation/$id': typeof AutomationIdRoute
  '/campaigns/$id': typeof CampaignsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/analisar': typeof AnalisarRoute
  '/automations': typeof AutomationsRoute
  '/campanhas': typeof CampanhasRoute
  '/dashboard': typeof DashboardRoute
  '/influencia': typeof InfluenciaRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/automation/$id': typeof AutomationIdRoute
  '/campaigns/$id': typeof CampaignsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/analisar'
    | '/automations'
    | '/campanhas'
    | '/dashboard'
    | '/influencia'
    | '/login'
    | '/settings'
    | '/automation/$id'
    | '/campaigns/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/analisar'
    | '/automations'
    | '/campanhas'
    | '/dashboard'
    | '/influencia'
    | '/login'
    | '/settings'
    | '/automation/$id'
    | '/campaigns/$id'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/analisar'
    | '/automations'
    | '/campanhas'
    | '/dashboard'
    | '/influencia'
    | '/login'
    | '/settings'
    | '/automation/$id'
    | '/campaigns/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AnalisarRoute: typeof AnalisarRoute
  AutomationsRoute: typeof AutomationsRoute
  CampanhasRoute: typeof CampanhasRoute
  DashboardRoute: typeof DashboardRoute
  InfluenciaRoute: typeof InfluenciaRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  AutomationIdRoute: typeof AutomationIdRoute
  CampaignsIdRoute: typeof CampaignsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/influencia': {
      id: '/influencia'
      path: '/influencia'
      fullPath: '/influencia'
      preLoaderRoute: typeof InfluenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analisar': {
      id: '/analisar'
      path: '/analisar'
      fullPath: '/analisar'
      preLoaderRoute: typeof AnalisarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$id': {
      id: '/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof CampaignsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/$id': {
      id: '/automation/$id'
      path: '/automation/$id'
      fullPath: '/automation/$id'
      preLoaderRoute: typeof AutomationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AnalisarRoute: AnalisarRoute,
  AutomationsRoute: AutomationsRoute,
  CampanhasRoute: CampanhasRoute,
  DashboardRoute: DashboardRoute,
  InfluenciaRoute: InfluenciaRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  AutomationIdRoute: AutomationIdRoute,
  CampaignsIdRoute: CampaignsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
