// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let { data } = await supabase.auth.getSession()
    // Token expired or missing — try to refresh before giving up
    if (!data.session?.access_token) {
      const refreshed = await supabase.auth.refreshSession()
      if (refreshed.data.session) data = refreshed.data
    }
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
